-- Rename an existing 22-table Italian-name schema without changing values.
-- For a 20-table schema or an already English schema, use tools/migrate_database_names.py.
-- Execute only once, before using the English TSV contract.
RENAME TABLE
ORGANISMO TO ORGANISM,
ORTOLOGIA_KEGG TO ORTHOLOGY_KEGG,
PATHWAY_RIFERIMENTO TO PATHWAY_REFERENCE,
REAZIONE_KEGG TO REACTION_KEGG,
COMPOSTO_KEGG TO COMPOUND_KEGG,
TERMINE_GO TO GO_TERM,
NUMERO_EC TO EC_NUMBER,
PATHWAY_ORGANISMO TO PATHWAY_ORGANISM,
GENE_PROTEINA TO GENE_PROTEIN,
GENE_ORTOLOGIA TO GENE_ORTHOLOGY,
ORTOLOGIA_REAZIONE TO ORTHOLOGY_REACTION,
PATHWAY_REAZIONE TO PATHWAY_REACTION,
REAZIONE_COMPOSTO TO REACTION_COMPOUND,
PROTEINA_GO TO PROTEIN_GO,
PROTEINA_EC TO PROTEIN_EC,
REAZIONE_EC TO REACTION_EC,
ORTOLOGIA_PATHWAY TO ORTHOLOGY_PATHWAY,
ORTOLOGIA_EC TO ORTHOLOGY_EC;
