-- Load ORGANISM.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/organism.tsv'
INTO TABLE ORGANISM
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(organism_id, kegg_code, taxonomy_id, scientific_name);

-- Load ORTHOLOGY_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/orthology_kegg.tsv'
INTO TABLE ORTHOLOGY_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ko_id, @name, @definition)
SET name = IF(OCTET_LENGTH(@name) = 0, NULL, @name), definition = IF(OCTET_LENGTH(@definition) = 0, NULL, @definition);

-- Load PATHWAY_REFERENCE.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/pathway_reference.tsv'
INTO TABLE PATHWAY_REFERENCE
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(map_id, name);

-- Load REACTION_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/reaction_kegg.tsv'
INTO TABLE REACTION_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(reaction_id, @name, @definition, @equation)
SET name = IF(OCTET_LENGTH(@name) = 0, NULL, @name), definition = IF(OCTET_LENGTH(@definition) = 0, NULL, @definition), equation = IF(OCTET_LENGTH(@equation) = 0, NULL, @equation);

-- Load COMPOUND_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/compound_kegg.tsv'
INTO TABLE COMPOUND_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(compound_id, name, @formula, @exact_mass, @molecular_weight)
SET formula = IF(OCTET_LENGTH(@formula) = 0, NULL, @formula), exact_mass = IF(OCTET_LENGTH(@exact_mass) = 0, NULL, @exact_mass), molecular_weight = IF(OCTET_LENGTH(@molecular_weight) = 0, NULL, @molecular_weight);

-- Load GO_TERM.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/go_term.tsv'
INTO TABLE GO_TERM
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(go_id, name, namespace);

-- Load EC_NUMBER.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/ec_number.tsv'
INTO TABLE EC_NUMBER
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ec_number);

-- Load GENE_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_kegg.tsv'
INTO TABLE GENE_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, organism_id, gene_type, @symbol, @definition)
SET symbol = IF(OCTET_LENGTH(@symbol) = 0, NULL, @symbol), definition = IF(OCTET_LENGTH(@definition) = 0, NULL, @definition);

-- Load PROTEIN_UNIPROT.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/protein_uniprot.tsv'
INTO TABLE PROTEIN_UNIPROT
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(accession, organism_id, entry_name, @protein_name, sequence_length, molecular_mass, protein_existence, sequence_version, amino_acid_sequence)
SET protein_name = IF(OCTET_LENGTH(@protein_name) = 0, NULL, @protein_name);

-- Load PATHWAY_ORGANISM.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/pathway_organism.tsv'
INTO TABLE PATHWAY_ORGANISM
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(pathway_id, organism_id, map_id);

-- Load PROTEIN_ISOFORM.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/protein_isoform.tsv'
INTO TABLE PROTEIN_ISOFORM
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(isoform_id, accession, ordinal, name, sequence_status, @note)
SET note = IF(OCTET_LENGTH(@note) = 0, NULL, @note);

-- Load GENE_PROTEIN.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_protein.tsv'
INTO TABLE GENE_PROTEIN
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, accession, mapping_source);

-- Load GENE_ORTHOLOGY.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_orthology.tsv'
INTO TABLE GENE_ORTHOLOGY
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, ko_id);

-- Load GENE_PATHWAY.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_pathway.tsv'
INTO TABLE GENE_PATHWAY
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, pathway_id);

-- Load ORTHOLOGY_REACTION.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/orthology_reaction.tsv'
INTO TABLE ORTHOLOGY_REACTION
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ko_id, reaction_id);

-- Load PATHWAY_REACTION.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/pathway_reaction.tsv'
INTO TABLE PATHWAY_REACTION
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(map_id, reaction_id);

-- Load REACTION_COMPOUND.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/reaction_compound.tsv'
INTO TABLE REACTION_COMPOUND
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(reaction_id, compound_id);

-- Load PROTEIN_GO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/protein_go.tsv'
INTO TABLE PROTEIN_GO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(accession, go_id, @evidence_code, @evidence_source)
SET evidence_code = IF(OCTET_LENGTH(@evidence_code) = 0, NULL, @evidence_code), evidence_source = IF(OCTET_LENGTH(@evidence_source) = 0, NULL, @evidence_source);

-- Load PROTEIN_EC.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/protein_ec.tsv'
INTO TABLE PROTEIN_EC
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(accession, ec_number);

-- Load REACTION_EC.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/reaction_ec.tsv'
INTO TABLE REACTION_EC
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(reaction_id, ec_number);

-- Load ORTHOLOGY_PATHWAY.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/orthology_pathway.tsv'
INTO TABLE ORTHOLOGY_PATHWAY
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ko_id, map_id);

-- Load ORTHOLOGY_EC.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/orthology_ec.tsv'
INTO TABLE ORTHOLOGY_EC
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ko_id, ec_number);
