-- Load ORGANISMO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/organismo.tsv'
INTO TABLE ORGANISMO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(organism_id, kegg_code, taxonomy_id, scientific_name);

-- Load ORTOLOGIA_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/ortologia_kegg.tsv'
INTO TABLE ORTOLOGIA_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ko_id, @name, @definition)
SET name = NULLIF(@name, ''), definition = NULLIF(@definition, '');

-- Load PATHWAY_RIFERIMENTO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/pathway_riferimento.tsv'
INTO TABLE PATHWAY_RIFERIMENTO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(map_id, name);

-- Load REAZIONE_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/reazione_kegg.tsv'
INTO TABLE REAZIONE_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(reaction_id, @name, @definition, @equation)
SET name = NULLIF(@name, ''), definition = NULLIF(@definition, ''), equation = NULLIF(@equation, '');

-- Load COMPOSTO_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/composto_kegg.tsv'
INTO TABLE COMPOSTO_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(compound_id, name, @formula, @exact_mass, @molecular_weight)
SET formula = NULLIF(@formula, ''), exact_mass = NULLIF(@exact_mass, ''), molecular_weight = NULLIF(@molecular_weight, '');

-- Load TERMINE_GO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/termine_go.tsv'
INTO TABLE TERMINE_GO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(go_id, name, namespace);

-- Load NUMERO_EC.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/numero_ec.tsv'
INTO TABLE NUMERO_EC
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ec_number);

-- Load GENE_KEGG.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_kegg.tsv'
INTO TABLE GENE_KEGG
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, organism_id, gene_type, @symbol, @definition)
SET symbol = NULLIF(@symbol, ''), definition = NULLIF(@definition, '');

-- Load PROTEIN_UNIPROT.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/protein_uniprot.tsv'
INTO TABLE PROTEIN_UNIPROT
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(accession, organism_id, entry_name, @protein_name, sequence_length, molecular_mass, protein_existence, sequence_version, amino_acid_sequence)
SET protein_name = NULLIF(@protein_name, '');

-- Load PATHWAY_ORGANISMO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/pathway_organismo.tsv'
INTO TABLE PATHWAY_ORGANISMO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(pathway_id, organism_id, map_id);

-- Load PROTEIN_ISOFORM.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/protein_isoform.tsv'
INTO TABLE PROTEIN_ISOFORM
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(isoform_id, accession, ordinal, name, sequence_status, @note)
SET note = NULLIF(@note, '');

-- Load GENE_PROTEINA.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_proteina.tsv'
INTO TABLE GENE_PROTEINA
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, accession, mapping_source);

-- Load GENE_ORTOLOGIA.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_ortologia.tsv'
INTO TABLE GENE_ORTOLOGIA
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, ko_id);

-- Load GENE_PATHWAY.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/gene_pathway.tsv'
INTO TABLE GENE_PATHWAY
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(kegg_gene_id, pathway_id);

-- Load ORTOLOGIA_REAZIONE.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/ortologia_reazione.tsv'
INTO TABLE ORTOLOGIA_REAZIONE
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(ko_id, reaction_id);

-- Load PATHWAY_REAZIONE.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/pathway_reazione.tsv'
INTO TABLE PATHWAY_REAZIONE
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(map_id, reaction_id);

-- Load REAZIONE_COMPOSTO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/reazione_composto.tsv'
INTO TABLE REAZIONE_COMPOSTO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(reaction_id, compound_id);

-- Load PROTEINA_GO.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/proteina_go.tsv'
INTO TABLE PROTEINA_GO
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(accession, go_id, @evidence_code, @evidence_source)
SET evidence_code = NULLIF(@evidence_code, ''), evidence_source = NULLIF(@evidence_source, '');

-- Load PROTEINA_EC.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/proteina_ec.tsv'
INTO TABLE PROTEINA_EC
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(accession, ec_number);

-- Load REAZIONE_EC.
LOAD DATA LOCAL INFILE '{{DATA_DIR}}/reazione_ec.tsv'
INTO TABLE REAZIONE_EC
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\n' IGNORE 1 LINES
(reaction_id, ec_number);
